# Generated by Django 6.0.1 on 2026-01-18 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educationapp", "0005_course_alter_student_class_assignment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="strat_date",
            new_name="start_date",
        ),
    ]
