# Generated by Django 6.0.1 on 2026-01-18 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educationapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField(max_length=255)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="educationapp.student"
                    ),
                ),
            ],
        ),
    ]
