# Generated by Django 6.0.1 on 2026-01-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educationapp", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
