"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---- Environment Detection ----
DJANGO_ENV = os.environ.get("DJANGO_ENV", "development")
IS_PRODUCTION = DJANGO_ENV == "production"

# ---- SECRET_KEY ----
if IS_PRODUCTION:
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]  # 未設定なら即 KeyError
else:
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY",
        "django-insecure-^b#poz5_$@t&i41u=1q^%wc_rvjy*tik5@io3&bp+ml17v)$-&",
    )

DEBUG = not IS_PRODUCTION

# ---- ALLOWED_HOSTS ----
if IS_PRODUCTION:
    _hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
    if not _hosts:
        raise ValueError("Production requires DJANGO_ALLOWED_HOSTS env var")
    ALLOWED_HOSTS = [h.strip() for h in _hosts.split(",")]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "helloapp",
    "bookapp",
    "todoapp",
    "educationapp",
    "appendixapp",
    "ninja",
    "corsheaders",
    "items",
    "ninja_jwt",
    'ninja_extra',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {"default": dj_database_url.config(default="sqlite:///db.sqlite3")}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ---- JWT Cookie Configuration ----
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_DOMAIN": os.environ.get("AUTH_COOKIE_DOMAIN", None),
    "AUTH_COOKIE_SECURE": IS_PRODUCTION,
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_SAMESITE": "Lax",
}

# ---- CORS Configuration ----
CORS_ALLOW_CREDENTIALS = True

if IS_PRODUCTION:
    _cors_origins = os.environ.get("CORS_ORIGINS", "")
    if not _cors_origins:
        raise ValueError("Production requires CORS_ORIGINS env var")
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",")]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

# ---- CSRF Configuration ----
if IS_PRODUCTION:
    _csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
    if not _csrf_origins:
        raise ValueError(
            "Production requires CSRF_TRUSTED_ORIGINS env var (needed for Django admin)"
        )
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",")]
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]


MESSAGE_LEVEL = message_constants.DEBUG

# 画像を表示する時のURL
MEDIA_URL = "/media/"

# 画像を保存する場所（os.path.join ではなく、スラッシュで繋げます）
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_REDIRECT_URL = "todo_list"

LOGOUT_REDIRECT_URL = "login"

# ---- Security Headers (Production Only) ----
if IS_PRODUCTION:
    SECURE_HSTS_SECONDS = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
