# Generated by Django 6.0 on 2025-12-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers"),
        ),
    ]
